// <auto-generated />
namespace Teste.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mudando1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mudando1));
        
        string IMigrationMetadata.Id
        {
            get { return "201809041343437_mudando1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
